<keyword,int>
<identifier,a1>
<punctuator,';'>
<keyword,char>
<identifier,b1>
<punctuator,';'>
<keyword,double>
<identifier,c1>
<punctuator,';'>
<keyword,int>
<identifier,a2>
<punctuator,'='>
<int_const,34>
<punctuator,','>
<identifier,b2>
<punctuator,'='>
<int_const,455>
<punctuator,';'>
<keyword,char>
<identifier,c2>
<punctuator,','>
<identifier,d2>
<punctuator,'='>
<character-constant,'f'>
<punctuator,';'>
<keyword,double>
<identifier,e2>
<punctuator,'='>
<floating-const,0.98>
<punctuator,','>
<identifier,f2>
<punctuator,'='>
<floating-const,9.648>
<punctuator,';'>
<keyword,int>
<identifier,arr>
<punctuator,'['>
<int_const,4>
<punctuator,']'>
<punctuator,';'>
<keyword,double>
<identifier,arr1>
<punctuator,'['>
<int_const,4>
<punctuator,']'>
<punctuator,'['>
<int_const,5>
<punctuator,']'>
<punctuator,';'>
<keyword,int>
<identifier,arr2>
<punctuator,'['>
<int_const,3>
<punctuator,']'>
<punctuator,'['>
<int_const,5>
<punctuator,']'>
<punctuator,'['>
<int_const,5>
<punctuator,']'>
<punctuator,';'>
<keyword,int>
<identifier,main>
<punctuator,'('>
<punctuator,')'>
<punctuator,'{'>
<identifier,a1>
<punctuator,'='>
<floating-const,3.4>
<punctuator,';'>
<identifier,c1>
<punctuator,'='>
<int_const,4>
<punctuator,';'>
<identifier,a1>
<punctuator,'='>
<identifier,c1>
<punctuator,'+'>
<floating-const,3.4>
<punctuator,'*'>
<identifier,e2>
<punctuator,';'>
<identifier,c1>
<punctuator,'='>
<identifier,a1>
<punctuator,'+'>
<int_const,3>
<punctuator,'+'>
<int_const,4>
<punctuator,'*'>
<identifier,a2>
<punctuator,';'>
<identifier,a>
<punctuator,'='>
<int_const,3>
<punctuator,'>'>
<int_const,4>
<punctuator,';'>
<identifier,a1>
<punctuator,'='>
<identifier,c1>
<punctuator,'+'>
<int_const,3>
<punctuator,'*'>
<identifier,e2>
<punctuator,';'>
<keyword,while>
<punctuator,'('>
<identifier,a1>
<punctuator,')'>
<punctuator,'{'>
<identifier,a1>
<punctuator,'--'>
<punctuator,';'>
<punctuator,'++'>
<identifier,b1>
<punctuator,';'>
<punctuator,'}'>
<keyword,for>
<punctuator,'('>
<identifier,i>
<punctuator,';'>
<identifier,i>
<punctuator,'<'>
<int_const,0>
<punctuator,';'>
<identifier,i>
<punctuator,'++'>
<punctuator,')'>
<punctuator,'{'>
<identifier,e2>
<punctuator,'='>
<identifier,a1>
<punctuator,'+'>
<floating-const,3.4>
<punctuator,';'>
<punctuator,'}'>
<punctuator,'}'>
