<keyword,int>
<identifier,a1>
<punctuator,';'>
<keyword,char>
<identifier,b1>
<punctuator,';'>
<keyword,double>
<identifier,c1>
<punctuator,';'>
<keyword,int>
<identifier,a2>
<punctuator,'='>
<int_const,34>
<punctuator,','>
<identifier,b2>
<punctuator,'='>
<int_const,455>
<punctuator,';'>
<keyword,char>
<identifier,c2>
<punctuator,','>
<identifier,d2>
<punctuator,'='>
<character-constant,'f'>
<punctuator,';'>
<keyword,double>
<identifier,e2>
<punctuator,'='>
<floating-const,0.98>
<punctuator,','>
<identifier,f2>
<punctuator,'='>
<floating-const,9.648>
<punctuator,';'>
<keyword,void>
<punctuator,'*'>
<identifier,a3>
<punctuator,','>
<punctuator,'*'>
<identifier,b3>
<punctuator,';'>
<keyword,int>
<punctuator,'*'>
<identifier,c3>
<punctuator,'='>
<int_const,0>
<punctuator,','>
<punctuator,'*'>
<identifier,d3>
<punctuator,';'>
<keyword,double>
<punctuator,'*'>
<identifier,e3>
<punctuator,','>
<identifier,f3>
<punctuator,'='>
<int_const,0>
<punctuator,';'>
<keyword,char>
<punctuator,'*'>
<identifier,g3>
<punctuator,'='>
<int_const,0>
<punctuator,','>
<identifier,h3>
<punctuator,'='>
<int_const,0>
<punctuator,';'>
<keyword,char>
<punctuator,'*'>
<identifier,str>
<punctuator,'='>
<string-literal,"just_a_test">
<punctuator,';'>
<keyword,int>
<identifier,arr>
<punctuator,'['>
<int_const,4>
<punctuator,']'>
<punctuator,';'>
<keyword,double>
<identifier,arr1>
<punctuator,'['>
<int_const,4>
<punctuator,']'>
<punctuator,'['>
<int_const,5>
<punctuator,']'>
<punctuator,';'>
<keyword,int>
<identifier,arr2>
<punctuator,'['>
<int_const,3>
<punctuator,']'>
<punctuator,'['>
<int_const,5>
<punctuator,']'>
<punctuator,'['>
<int_const,5>
<punctuator,']'>
<punctuator,';'>
<keyword,int>
<identifier,j>
<punctuator,';'>
<keyword,int>
<identifier,main>
<punctuator,'('>
<punctuator,')'>
<punctuator,'{'>
<identifier,a1>
<punctuator,'='>
<int_const,3>
<punctuator,';'>
<keyword,for>
<punctuator,'('>
<identifier,i>
<punctuator,';'>
<identifier,i>
<punctuator,'>'>
<int_const,0>
<punctuator,';'>
<identifier,i>
<punctuator,'--'>
<punctuator,')'>
<punctuator,'{'>
<identifier,e2>
<punctuator,'='>
<identifier,c1>
<punctuator,'+'>
<identifier,a1>
<punctuator,';'>
<punctuator,'}'>
<keyword,while>
<punctuator,'('>
<int_const,1>
<punctuator,')'>
<punctuator,'{'>
<identifier,a1>
<punctuator,'='>
<identifier,arr>
<punctuator,'['>
<int_const,1>
<punctuator,']'>
<punctuator,';'>
<identifier,arr>
<punctuator,'['>
<int_const,1>
<punctuator,']'>
<punctuator,'='>
<identifier,a1>
<punctuator,';'>
<identifier,arr>
<punctuator,'['>
<int_const,4>
<punctuator,']'>
<punctuator,'='>
<identifier,arr1>
<punctuator,'['>
<int_const,1>
<punctuator,']'>
<punctuator,'['>
<int_const,1>
<punctuator,']'>
<punctuator,'+'>
<int_const,2>
<punctuator,';'>
<keyword,for>
<punctuator,'('>
<identifier,j>
<punctuator,'='>
<int_const,8>
<punctuator,';'>
<identifier,j>
<punctuator,'>'>
<int_const,0>
<punctuator,';'>
<identifier,j>
<punctuator,'--'>
<punctuator,')'>
<punctuator,'{'>
<identifier,j>
<punctuator,'='>
<int_const,3>
<punctuator,';'>
<punctuator,'}'>
<punctuator,'}'>
<keyword,return>
<int_const,3>
<punctuator,';'>
<punctuator,'}'>
