<keyword,int>
<identifier,a>
<punctuator,';'>
<keyword,int>
<identifier,c>
<punctuator,';'>
<keyword,double>
<identifier,x>
<punctuator,';'>
<keyword,int>
<identifier,i>
<punctuator,';'>
<keyword,double>
<identifier,s>
<punctuator,';'>
<keyword,int>
<identifier,add1>
<punctuator,'('>
<keyword,double>
<identifier,a>
<punctuator,')'>
<punctuator,'{'>
<punctuator,'}'>
<keyword,int>
<identifier,main>
<punctuator,'('>
<punctuator,')'>
<punctuator,'{'>
<keyword,if>
<punctuator,'('>
<identifier,i>
<punctuator,'>'>
<int_const,3>
<punctuator,')'>
<identifier,c>
<punctuator,'='>
<int_const,3>
<punctuator,';'>
<keyword,if>
<punctuator,'('>
<identifier,i>
<punctuator,'<='>
<int_const,0>
<punctuator,')'>
<identifier,c>
<punctuator,'='>
<identifier,x>
<punctuator,';'>
<keyword,else>
<identifier,c>
<punctuator,'='>
<identifier,x>
<punctuator,';'>
<keyword,while>
<punctuator,'('>
<identifier,i>
<punctuator,'>'>
<int_const,0>
<punctuator,')'>
<punctuator,'{'>
<identifier,a>
<punctuator,'='>
<identifier,c>
<punctuator,'+'>
<identifier,a>
<punctuator,';'>
<identifier,i>
<punctuator,'++'>
<punctuator,';'>
<identifier,a>
<punctuator,'--'>
<punctuator,';'>
<punctuator,'}'>
<keyword,for>
<punctuator,'('>
<identifier,i>
<punctuator,'='>
<int_const,0>
<punctuator,';'>
<identifier,i>
<punctuator,'>'>
<int_const,0>
<punctuator,';'>
<identifier,i>
<punctuator,'++'>
<punctuator,')'>
<punctuator,'{'>
<identifier,c>
<punctuator,'='>
<identifier,a>
<punctuator,'+'>
<identifier,s>
<punctuator,'*'>
<int_const,3>
<punctuator,';'>
<identifier,s>
<punctuator,'='>
<identifier,c>
<punctuator,';'>
<identifier,s>
<punctuator,'--'>
<punctuator,';'>
<identifier,c>
<punctuator,'='>
<identifier,a>
<punctuator,';'>
<punctuator,'}'>
<keyword,do>
<punctuator,'{'>
<identifier,c>
<punctuator,'='>
<identifier,a>
<punctuator,'+'>
<identifier,s>
<punctuator,'*'>
<int_const,3>
<punctuator,';'>
<identifier,s>
<punctuator,'='>
<identifier,c>
<punctuator,';'>
<identifier,c>
<punctuator,'='>
<identifier,a>
<punctuator,';'>
<identifier,c>
<punctuator,'--'>
<punctuator,';'>
<identifier,a>
<punctuator,'='>
<identifier,a>
<punctuator,'+'>
<identifier,c>
<punctuator,';'>
<punctuator,'}'>
<keyword,while>
<punctuator,'('>
<identifier,a>
<punctuator,'>'>
<int_const,0>
<punctuator,')'>
<punctuator,';'>
<keyword,while>
<punctuator,'('>
<identifier,i>
<punctuator,')'>
<punctuator,'{'>
<identifier,a>
<punctuator,'='>
<identifier,c>
<punctuator,'+'>
<identifier,a>
<punctuator,';'>
<identifier,i>
<punctuator,'++'>
<punctuator,';'>
<punctuator,'}'>
<keyword,for>
<punctuator,'('>
<identifier,i>
<punctuator,'='>
<int_const,0>
<punctuator,';'>
<identifier,i>
<punctuator,';'>
<identifier,i>
<punctuator,'++'>
<punctuator,')'>
<punctuator,'{'>
<identifier,c>
<punctuator,'='>
<identifier,a>
<punctuator,'+'>
<identifier,s>
<punctuator,'*'>
<int_const,3>
<punctuator,';'>
<identifier,s>
<punctuator,'='>
<identifier,c>
<punctuator,';'>
<identifier,c>
<punctuator,'='>
<identifier,a>
<punctuator,';'>
<punctuator,'}'>
<keyword,do>
<punctuator,'{'>
<identifier,c>
<punctuator,'='>
<identifier,a>
<punctuator,'+'>
<identifier,s>
<punctuator,'*'>
<int_const,3>
<punctuator,';'>
<identifier,s>
<punctuator,'='>
<identifier,c>
<punctuator,';'>
<identifier,c>
<punctuator,'='>
<identifier,a>
<punctuator,';'>
<identifier,a>
<punctuator,'='>
<identifier,a>
<punctuator,'+'>
<identifier,c>
<punctuator,';'>
<punctuator,'}'>
<keyword,while>
<punctuator,'('>
<identifier,a>
<punctuator,')'>
<punctuator,';'>
<keyword,return>
<identifier,a>
<punctuator,';'>
<punctuator,'}'>
