<keyword,int>
<identifier,a>
<punctuator,';'>
<keyword,int>
<punctuator,'*'>
<identifier,ptra>
<punctuator,';'>
<keyword,int>
<identifier,a1>
<punctuator,','>
<identifier,a2>
<punctuator,';'>
<keyword,double>
<identifier,d1>
<punctuator,','>
<identifier,d2>
<punctuator,'='>
<floating-const,4.8>
<punctuator,';'>
<keyword,char>
<identifier,c>
<punctuator,';'>
<keyword,int>
<identifier,arr1>
<punctuator,'['>
<int_const,2>
<punctuator,']'>
<punctuator,','>
<identifier,arr2>
<punctuator,'['>
<int_const,3>
<punctuator,']'>
<punctuator,'['>
<int_const,4>
<punctuator,']'>
<punctuator,','>
<identifier,arr3>
<punctuator,'['>
<int_const,3>
<punctuator,']'>
<punctuator,'['>
<int_const,3>
<punctuator,']'>
<punctuator,'['>
<int_const,3>
<punctuator,']'>
<punctuator,';'>
<keyword,int>
<identifier,add1>
<punctuator,'('>
<keyword,int>
<identifier,a>
<punctuator,','>
<keyword,int>
<identifier,b>
<punctuator,')'>
<punctuator,';'>
<keyword,int>
<identifier,main>
<punctuator,'('>
<keyword,int>
<identifier,a>
<punctuator,','>
<keyword,double>
<identifier,d>
<punctuator,')'>
<punctuator,'{'>
<identifier,a>
<punctuator,'='>
<int_const,4>
<punctuator,';'>
<identifier,d>
<punctuator,'='>
<floating-const,2.5>
<punctuator,';'>
<identifier,c>
<punctuator,'='>
<character-constant,'f'>
<punctuator,';'>
<identifier,a>
<punctuator,'='>
<int_const,5>
<punctuator,'+'>
<int_const,3>
<punctuator,'*'>
<identifier,a1>
<punctuator,'+'>
<identifier,a>
<punctuator,';'>
<identifier,d1>
<punctuator,'='>
<identifier,d1>
<punctuator,'/'>
<floating-const,2.3>
<punctuator,'*'>
<identifier,d2>
<punctuator,';'>
<identifier,d2>
<punctuator,'++'>
<punctuator,';'>
<identifier,a1>
<punctuator,'++'>
<punctuator,';'>
<identifier,a1>
<punctuator,'='>
<identifier,a1>
<punctuator,'<<'>
<int_const,4>
<punctuator,';'>
<identifier,a2>
<punctuator,'='>
<identifier,a2>
<punctuator,'>>'>
<int_const,3>
<punctuator,';'>
<punctuator,'--'>
<identifier,a>
<punctuator,';'>
<punctuator,'++'>
<identifier,a>
<punctuator,';'>
<identifier,c>
<punctuator,'='>
<identifier,add1>
<punctuator,'('>
<identifier,a>
<punctuator,','>
<identifier,b>
<punctuator,')'>
<punctuator,';'>
<identifier,a>
<punctuator,'='>
<identifier,d>
<punctuator,';'>
<identifier,a>
<punctuator,'='>
<identifier,arr1>
<punctuator,'['>
<int_const,3>
<punctuator,']'>
<punctuator,';'>
<identifier,a1>
<punctuator,'='>
<identifier,arr2>
<punctuator,'['>
<int_const,2>
<punctuator,']'>
<punctuator,'['>
<int_const,1>
<punctuator,']'>
<punctuator,';'>
<identifier,a2>
<punctuator,'='>
<identifier,arr3>
<punctuator,'['>
<int_const,0>
<punctuator,']'>
<punctuator,'['>
<int_const,1>
<punctuator,']'>
<punctuator,'['>
<int_const,2>
<punctuator,']'>
<punctuator,';'>
<identifier,arr2>
<punctuator,'['>
<int_const,2>
<punctuator,']'>
<punctuator,'['>
<int_const,1>
<punctuator,']'>
<punctuator,'='>
<identifier,arr3>
<punctuator,'['>
<int_const,1>
<punctuator,']'>
<punctuator,'['>
<int_const,2>
<punctuator,']'>
<punctuator,'['>
<int_const,2>
<punctuator,']'>
<punctuator,';'>
<identifier,d1>
<punctuator,'='>
<identifier,d1>
<punctuator,'/'>
<identifier,d2>
<punctuator,'+'>
<identifier,d1>
<punctuator,'%'>
<identifier,d2>
<punctuator,';'>
<identifier,a>
<punctuator,'='>
<int_const,2>
<punctuator,'>'>
<int_const,5>
<punctuator,';'>
<identifier,d>
<punctuator,'='>
<int_const,4>
<punctuator,'<'>
<int_const,3>
<punctuator,';'>
<identifier,a>
<punctuator,'='>
<identifier,a1>
<punctuator,'^'>
<identifier,a2>
<punctuator,';'>
<identifier,a1>
<punctuator,'='>
<punctuator,'('>
<int_const,3>
<punctuator,'>'>
<identifier,a>
<punctuator,')'>
<punctuator,'?'>
<identifier,a1>
<punctuator,':'>
<identifier,a>
<punctuator,';'>
<identifier,d1>
<punctuator,'='>
<identifier,add1>
<punctuator,'('>
<identifier,a1>
<punctuator,','>
<identifier,a2>
<punctuator,')'>
<punctuator,';'>
<punctuator,'}'>
