<keyword,int>
<identifier,a1>
<punctuator,';'>
<keyword,char>
<identifier,b1>
<punctuator,';'>
<keyword,double>
<identifier,c1>
<punctuator,';'>
<keyword,int>
<identifier,a2>
<punctuator,'='>
<int_const,34>
<punctuator,','>
<identifier,b2>
<punctuator,'='>
<int_const,455>
<punctuator,';'>
<keyword,char>
<identifier,c2>
<punctuator,','>
<identifier,d2>
<punctuator,'='>
<character-constant,'f'>
<punctuator,';'>
<keyword,double>
<identifier,e2>
<punctuator,'='>
<floating-const,0.98>
<punctuator,','>
<identifier,f2>
<punctuator,'='>
<floating-const,9.648>
<punctuator,';'>
<keyword,void>
<punctuator,'*'>
<identifier,a3>
<punctuator,','>
<punctuator,'*'>
<identifier,b3>
<punctuator,';'>
<keyword,int>
<punctuator,'*'>
<identifier,c3>
<punctuator,'='>
<int_const,0>
<punctuator,','>
<punctuator,'*'>
<identifier,d3>
<punctuator,';'>
<keyword,double>
<punctuator,'*'>
<identifier,e3>
<punctuator,','>
<identifier,f3>
<punctuator,'='>
<int_const,0>
<punctuator,';'>
<keyword,char>
<punctuator,'*'>
<identifier,g3>
<punctuator,'='>
<int_const,0>
<punctuator,','>
<identifier,h3>
<punctuator,'='>
<int_const,0>
<punctuator,';'>
<keyword,char>
<punctuator,'*'>
<identifier,str>
<punctuator,'='>
<string-literal,"just_a_test">
<punctuator,';'>
<keyword,int>
<identifier,arr>
<punctuator,'['>
<int_const,4>
<punctuator,']'>
<punctuator,';'>
<keyword,double>
<identifier,arr1>
<punctuator,'['>
<int_const,4>
<punctuator,']'>
<punctuator,'['>
<int_const,5>
<punctuator,']'>
<punctuator,';'>
<keyword,int>
<identifier,arr2>
<punctuator,'['>
<int_const,3>
<punctuator,']'>
<punctuator,'['>
<int_const,5>
<punctuator,']'>
<punctuator,'['>
<int_const,5>
<punctuator,']'>
<punctuator,';'>
<keyword,int>
<identifier,add1>
<punctuator,'('>
<punctuator,')'>
<punctuator,';'>
<keyword,void>
<identifier,add2>
<punctuator,'('>
<punctuator,')'>
<punctuator,';'>
<keyword,char>
<identifier,add2>
<punctuator,'('>
<punctuator,')'>
<punctuator,';'>
<keyword,int>
<identifier,add3>
<punctuator,'('>
<keyword,int>
<punctuator,'*'>
<identifier,a>
<punctuator,','>
<keyword,int>
<identifier,b>
<punctuator,','>
<keyword,int>
<identifier,c>
<punctuator,')'>
<punctuator,';'>
<keyword,void>
<identifier,add4>
<punctuator,'('>
<keyword,int>
<identifier,a>
<punctuator,','>
<keyword,double>
<punctuator,'*'>
<identifier,b>
<punctuator,','>
<keyword,int>
<identifier,su>
<punctuator,')'>
<punctuator,';'>
<keyword,int>
<identifier,add5>
<punctuator,'('>
<keyword,double>
<identifier,a>
<punctuator,','>
<keyword,char>
<punctuator,'*'>
<identifier,b>
<punctuator,')'>
<punctuator,';'>
<keyword,int>
<punctuator,'*'>
<identifier,test6>
<punctuator,'('>
<punctuator,')'>
<punctuator,';'>
<keyword,void>
<punctuator,'*'>
<identifier,test5>
<punctuator,'('>
<punctuator,')'>
<punctuator,';'>
<keyword,char>
<punctuator,'*'>
<identifier,test4>
<punctuator,'('>
<punctuator,')'>
<punctuator,';'>
<keyword,int>
<punctuator,'*'>
<identifier,test3>
<punctuator,'('>
<keyword,int>
<identifier,a>
<punctuator,','>
<keyword,int>
<identifier,b>
<punctuator,','>
<keyword,int>
<identifier,c>
<punctuator,')'>
<punctuator,';'>
<keyword,void>
<punctuator,'*'>
<identifier,test2>
<punctuator,'('>
<keyword,int>
<identifier,a>
<punctuator,','>
<keyword,double>
<punctuator,'*'>
<identifier,b>
<punctuator,','>
<keyword,int>
<identifier,su>
<punctuator,')'>
<punctuator,';'>
<keyword,int>
<punctuator,'*'>
<identifier,test1>
<punctuator,'('>
<keyword,double>
<identifier,a>
<punctuator,','>
<keyword,char>
<identifier,b>
<punctuator,')'>
<punctuator,';'>
<keyword,void>
<identifier,func>
<punctuator,'('>
<keyword,int>
<identifier,i>
<punctuator,','>
<keyword,double>
<identifier,d>
<punctuator,')'>
<punctuator,';'>
